[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install --omit=optional --no-audit --prefer-offline || npm install --omit=optional --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"
